### ISSUE TITLE
Is this stable?

### ISSUE THREAD

**Issue by Noir-** [KyleMcNutt/angular-todo-demo#1]
If really like this tutorial! It's pretty awesome for me as a beginner since it's hard to find any well build application out there which follows the latest best practices. I'd like to use this as a kind of boiler plate for own projects but I'd like to wait until it's stable. Since I'm new to AngularJS it's hard for me to say weather it's the case or not. (Of course I wouldn't blame you if anything goes wrong)

**Comment by KyleBastien** [comment]
Hey Noir, really glad you like this tutorial. I'm also thinking about putting together blog posts that go through each step and explain in further detail what I'm doing.

In terms of stability, this is a good question. After the last commit I pushed to refactor the Todo List from a static JSON file to a Service using Local Storage it's got pretty much all the main features I'm looking to add to it. And as far as I'm aware I don't have any major bugs.

Next steps are probably going to be:
1. Clean up the UI and make it look pretty
2. Add Testing with Karma and Jasmine
3. Create a backend api of some kind (this isn't fleshed out in my head yet I just know that I
   wana show what it's like to hit a real API)

If you don't think any of those things are going to strongly effect your using this as a boiler plate than go for it. If there are any bugs you run into please feel free to drop an issue here and I'll fix it ASAP.

Now if you want something a little more fleshed out than this is, feel free to check out [John Papa's Angular HotTowel Generator](https://github.com/johnpapa/generator-hottowel). The reason that I made this repo though is that I thought John's generator was a little to feature rich, and I wanted something with more of just the bare bones of what I need to get started on a project.

Also if your new to AngularJS be sure to check out [John Papa's Angular Style Guide](https://github.com/johnpapa/angular-styleguide/blob/master/a1/README.md). I know its long but seriously read the whole thing. It comes close to be being my bible while developing Angular apps and is the style that I try my best and hardest to follow throughout this little todo-demo.

Also of your looking for a Todo Application that is a little more fleshed out checkout [TodoMVC](https://github.com/tastejs/todomvc/tree/gh-pages/examples/angularjs). But fair warning that application breaks a whole tun of best practices and isn't the best learning resource, IMHO.

To answer your original question, I think this repo has gotten to the point that it is relatively stable, but I will continue to work on it and make it better. I will also update it as best practices change in order to make sure this repo is up to date. Like I said always feel free to drop me an issue or pull request if you find anything that's wrong and I'll do best to fix it ASAP.

**Comment by Noir-** [comment]
This is a pleasure to hear and I'm already tinkering with it.

To see the consumption of a server side API would be really interesting since I'm already stuck with it. My scenario is that I want to create a service with some basic data which should be accessed through multiple controllers. The service should be initialized with data from an API. As far as I know I would need to use the `resolve` option in the ui-router config but I didn't get it working at the moment. Do you think this is a scenario which is common enough to be covered by this tutorial?

**Comment by KyleBastien** [comment]
@Noir- Hitting an API, like what your talking about is, without a doubt a scenario that I want to cover in this tutorial. Since you requested it I'll try and re-prioritize this and have the example up here by the end of the weekend.

Now, if you want something to at least get you started you could look at the code from [Step 7](https://github.com/KyleMcNutt/angular-todo-demo/commit/de23a65f8005108699dba14516350ea9ff2657e6) and the code from [Step 8](https://github.com/KyleMcNutt/angular-todo-demo/commit/dbd826d2516f733bc994ebb352076d6c210a4e8b) in order to get an idea of how to do this.

Basically you want to create a Service, using `angular.module(..).factory(..)`, which uses the Angular `$http` Service in order to get data from your API.

You can then `$inject` your newly created Service into any controller that you want and call those methods from there, and populate your `vm` with what you get back.

I would definitely start with Step 7 as this shows how to use the `$http` service, which is probably what your going to do. Step 8 shows a similar process but I'm using the browsers localStorage instead of `$http`.

Let me know if that doesn't make sense, or if there are any further questions you have.

**Comment by KyleBastien** [comment]
I also updated my first comment with links to the resources that I was talking about, in case you want to take a look at those.

**Comment by KyleBastien** [comment]
@Noir- I just added the ability to hit a real backend API from this Angular application in the latest commit.

You can check out `dotnetstorage.service.js` in order to see the implementation. For the scenario that you described above you could `$inject` this Service into any Controller you want and use it similar to how I'm using it in `todo.controller.js`.

In order to see this in action your going to want to change `storageservice.constant.js` to say `Dot Net Api` instead of `Local Storage` on line `8`.

Also if you want to look at what the actual API itself looks like feel free to check out my new [TodoApi Repo](https://github.com/KyleMcNutt/dotnet-core-todo-api).

I'm gonna go ahead and close this Issue since I think I've answered your question as best I can. If there is something I missed feel free to re-open this issues and let me know.
